### ISSUE TITLE
Broken on 3.0.0 beta

### ISSUE THREAD

**Issue by etiennea** [ShaneK/Matador#42]
```
2017-05-25T14:05:44.041Z - error: uncaughtException: failedJobs.keys[explodedKeys[1]].indexOf is not a function date=Thu May 25 2017 15:05:44 GMT+0100 (BST), pid=92140, uid=501, gid=20, cwd=/Users/etienne/Github/panelise/express, execPath=/usr/local/bin/node, version=v6.9.4, argv=[/usr/local/bin/node, /Users/etienne/Github/panelise/express/bin/www], rss=76759040, heapTotal=67305472, heapUsed=56975568, loadavg=[3.0810546875, 3.7080078125, 3.27099609375], uptime=1452267, trace=[column=106, file=/Users/etienne/Github/panelise/express/node_modules/bull-ui/models/redis.js, function=null, line=230, method=null, native=false, column=54, file=/Users/etienne/Github/panelise/express/node_modules/q/q.js, function=_fulfilled, line=794, method=null, native=false, column=30, file=/Users/etienne/Github/panelise/express/node_modules/q/q.js, function=self.promiseDispatch.done, line=823, method=promiseDispatch.done, native=false, column=13, file=/Users/etienne/Github/panelise/express/node_modules/q/q.js, function=Promise.promise.promiseDispatch, line=756, method=promise.promiseDispatch, native=false, column=44, file=/Users/etienne/Github/panelise/express/node_modules/q/q.js, function=null, line=564, method=null, native=false, column=17, file=/Users/etienne/Github/panelise/express/node_modules/q/q.js, function=flush, line=110, method=null, native=false, column=7, file=internal/process/next_tick.js, function=_combinedTickCallback, line=67, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickDomainCallback, line=122, method=_tickDomainCallback, native=false], stack=[TypeError: failedJobs.keys[explodedKeys[1]].indexOf is not a function,     at /Users/etienne/Github/express/node_modules/bull-ui/models/redis.js:230:106,     at _fulfilled (/Users/etienne/Github/express/node_modules/q/q.js:794:54),     at self.promiseDispatch.done (/Users/etienne/Github/express/node_modules/q/q.js:823:30),     at Promise.promise.promiseDispatch (/Users/etienne/Github/express/node_modules/q/q.js:756:13),     at /Users/etienne/Github/express/node_modules/q/q.js:564:44,     at flush (/Users/etienne/Github/express/node_modules/q/q.js:110:17),     at _combinedTickCallback (internal/process/next_tick.js:67:7),     at process._tickDomainCallback (internal/process/next_tick.js:122:9)]
Program node ./bin/www exited with code 1
```

**Comment by ritter** [comment]
Related to 3.0.0 (currently 3.0.0-rc.2) ... I'm also getting:

> Unhandled rejection ReplyError: WRONGTYPE Operation against a key holding the wrong kind of value
     at parseError (./node_modules/redis-parser/lib/parser.js:193:12)
     at parseType (./node_modules/redis-parser/lib/parser.js:303:14)

**Comment by stolendog** [comment]
do you know when it will be fixed?

**Comment by Furzel** [comment]
I made a fork fixing this issue here : https://github.com/Furzel/Matador 

It's been running without issue for a short week now on my side and I haven't noticed any issue. 

Note that if you switched to bull 2.* to 3.* without cleaning your redis you might have some queues still using sets instead of zsets so they will still break on my fixed version.
